# -*- coding: utf-8 -*-
"""shape ai project (weather).py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vdau6XCHnPK0_dW1hYkswGS1T6imCV3L
"""

import requests
#import as 
from datetime import datetime

api_key = '00ef06c52ca9dbc727ff1bc505c4652d'
location = input("enter the city name: ")

complete_api_link ="https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("current temperature is: {:.2f} deg C".format(temp_city))
print ("current weather desc  :",weather_desc)
print ("current humidity      :",hmdt, '%')
print ("current wind speed    :",wind_spd ,'kmph')

f = open("result.txt","w")
f.write("api_link.json()")
f.close()